# Generated by Django 4.1.2 on 2022-10-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
