# Generated by Django 4.1.2 on 2022-10-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='roll',
        ),
    ]
