# Generated by Django 4.1.2 on 2022-10-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compname', models.CharField(max_length=64)),
                ('recruitername', models.CharField(max_length=64)),
                ('compemail', models.EmailField(max_length=64)),
                ('complink', models.URLField(max_length=64)),
            ],
        ),
    ]
